### ISSUE TITLE
Revisar diagrama de classes

### ISSUE THREAD

**Issue by rdalbuquerque** [ESEGroup/Venezuela#11]
verificar se ta faltando alguma classe/atributo e/ou se tem alguma relação entre classes muito estranha

**Comment by ghost** [comment]
É aquele diagrama que você levou ontem? Por que falta mexer nos atributos do aluno\funcionário e visitante.

**Comment by rdalbuquerque** [comment]
entao, ja atualizei com oq  a gnt tinha falado, eh p ve se ta faltando mais
alguma coisa mesmo.

2016-11-11 18:26 GMT-02:00 DanielBlue1 notifications@github.com:

**Comment by ghost** [comment]
É que quando abri aqui estava igual ao d ontem, com  aluno\funcionário\visitante com msm atributos do usuário.

**Comment by rdalbuquerque** [comment]
Huum é q não é mais o v1, vo postar o pdf do atualizado

Em 11 de nov de 2016 6:34 PM, "DanielBlue1" notifications@github.com
escreveu:

**Comment by ghost** [comment]
E falta colocar as açoes tbm nesse diagrama. Agora que vi.... D:

**Comment by marielen** [comment]
@rodolfo-albuquerque abaixo coloquei as minhas considerações referentes ao diagrama de classe #4 .
- Acho que não precisa ter classes para visitante, ele não tem nada diferente da classe usuário.
- Na classe funcionário acho que poderia ter o atributo do número de matrícula que é algo que só funcionário da UFRJ teria. O único detalhe é que terceirizados acho que não teriam.
- Na relação entre o usuário e a ocorrência em vez de 0..._, acho melhor colocar 1..._, pois é preciso criar pelo menos uma ocorrência.
- Na classe do histórico acho que deve ter relação com a classe estado e ter um atributo chamado mensagem, pois quando um funcionário de segurança alterar o estado de uma ocorrência, ele deve escrever algo.
- Não entendi pq a necessidade da classe UFRJ, nem da cadastro.
- Não entendi pq tem que ter relação da classe gestor com o funcionário de segurança. Se tiver mesmo, acho que tem que ser mais fraca, tipo uma simples associação.
- O funcionário de segurança também não deveria ter acesso ao relatório?

**Comment by rdalbuquerque** [comment]
4 primeiros itens concordados, farei as modificações.

_"Não entendi pq a necessidade da classe UFRJ, nem da cadastro"._
A classe UFRJ eu também achei meio desnecessário mas não sei porque não
coloca-la.

A classe cadastro entrou devido aos casos de uso "solicitação de cadastro"
e aprovação de cadastro". No caso, gestor e funcionário de segurança
trocariam mensagem com essa classe cadastro.

"N_ão entendi pq tem que ter relação da classe gestor com o funcionário de
segurança. Se tiver mesmo, acho que tem que ser mais fraca, tipo uma
simples associação_."
Eu coloquei gestor como subclasse de funcionário de segurança pois ele
possui todos os atributos e a maioria dos métodos de funcionário de
segurança, dessa forma reutilizando esses itens. Pelo que conversei com
Hilmer, simples associação não caracteriza a relação o suficiente.

"_O funcionário de segurança também não deveria ter acesso ao relatório?_"
Na nossa especificação de caso de uso, o único ator de do UC "Geração de
relatório" é o gestor. O funcionário de segurança teria acesso ao relatório
posteriormente, mas creio que isso não caracteriza uma relação entre as
classes.

2016-11-14 10:44 GMT-02:00 Marielen Ferreira notifications@github.com:

**Comment by marielen** [comment]
@rodolfo-albuquerque realmente concordo com as suas considerações.

**Comment by marielen** [comment]
@rodolfo-albuquerque Acabei de ver que tem um bug no início da imagem.

E não seria melhor se as setas fossem retas?
