### ISSUE TITLE
Revisão dos Diagramas de Sequência

### ISSUE THREAD

**Issue by ghost** [ESEGroup/Venezuela#15]
Analisar os diagramas, verificando se falta algum elemento ou ação faltando.

**Comment by marielen** [comment]
@DanielBlue1 abaixo coloquei as minhas considerações referentes ao seus diagramas de sequência.

Diagrama de sequência #3 - Login
- No ator que realiza login não poderia ser tanto o funcionário de segurança quanto o gestor? Acho que essa informação poderia ser adicionada abaixo de funcionário de segurança.
- Em vez de ter quatro mensagens sendo enviadas à Tela de Login poderia ter uma só do tipo solicita_acesso(cpf,senha). Vi isso no exemplo que está no arquivo ee873_modelos_uml_2.pdf
  do moodle na página 17.
- Acredito que existe um padrão das mensagens. Pelo que eu vi no pdf sempre são escritas com letras minúsculas e com underline no lugar de espaço.
- E pq vc mudou o estilo das setas? Achava que todas deveriam ser iguais como a primeira que vc colocou.
- O controle se representa com esse loop mesmo? Não faço ideia, achava que fosse sempre um retângulo.
- O nome de cada objeto tb não tem um padrão? Mas comparando o exemplo do pdf com esse diagrama fico um pouco na dúvida de como ficaria.
- Não teria que ter algum texto nas setas que estão voltando para o funcionário de segurança? Poderia ser tipo "Autoriza acesso"

Diagrama de sequência #3 - Alteração de Senha
- Em vez de mostrar 5 mensagens para solicitar a alteração de senha, poderia ter uma só do tipo alterar_senha(senha_antiga,senha_nova,confirmacao_senha).
- Aliás, acho que senha_digitadas_iguais(senha_nova, confirmacao_senha) deva acontecer antes de confirma_senha_antiga(senha_antiga).
- Padrão do nome das mensagens (como dito no DS-Login)
- Ícone dos objetos (como dito no DS-Login)
- Formato das setas (como dito no DS-Login)

**Comment by rdalbuquerque** [comment]
Marielen, no diagrama de classes gestor é subclasse de funcionário de
segurança, acho que por isso que ele colocou apenas funcionário de
segurança no login/alteração de senha.

Quanto as setas eu li na pagina da IBM que tem mensagens sincronas e
assincronas, acho que foi isso que ele quis representar. também vi
mensagens de volta com e sem texto, mas acho que caberia texto sim.

Em 14 de novembro de 2016 10:20, Marielen Ferreira <notifications@github.com

**Comment by ghost** [comment]
Diagrama de Sequência #3 - Login
- Ator é funcionário de segurança, porque gestor é uma subclasse dele.
- Posso por uma mensagem genérica, mas achei que especificando melhor os dados inseridos ficaria mais fácil para elaboração da interface. Nessa fase achei que era bom detalhar essa parte.
- Realmente existe padrão no nome das mensagens... é mais pra quando for escrever o programa seguir esse msm padrão de nome no nomes das funções.
- O formato das setas tem a ver com o programa, mensagem síncronas tem setas diferentes de assíncronas. 
- Sim, o controle tem aquele simbolo lá mesmo. Mas também pode colocar tudo como retângulo. coloquei desse jeito para diferenciar.
- Na mensagem de retorno, achei q n precisava de texto, pois esta funcionando de forma síncrona, aguardando a resposta da função.

Diagrama de sequência #3 - Alteração de Senha:
- Mesmo caso ali em cima, mostrei varias mensagens para facilitar na hora de confeccionar a interface.
-  A ordem de verificação das senhas não importa muito, pois a resposta resposta para a operação retorna só no final. Ele meio que verifica os 2, antes de retornar com o resultado. 
- Padrão na hora de nomear as mensagens, vou arrumar.
- Ícone dos objetos (como dito no diagrama de login).
- Formato das setas (como dito no Diagramde de login).

**Comment by marielen** [comment]
Ainda tenho algumas considerações:

> Posso por uma mensagem genérica, mas achei que especificando melhor os dados inseridos ficaria mais fácil para elaboração da interface. Nessa fase achei que era bom detalhar essa parte.

Acho que é melhor simplificar, pois desse jeito o fluxo fica contínuo.

> Na mensagem de retorno, achei q n precisava de texto, pois esta funcionando de forma síncrona, aguardando a resposta da função.

Acho que realmente é melhor deixar explícito nesse caso.

> A ordem de verificação das senhas não importa muito, pois a resposta resposta para a operação retorna só no final. Ele meio que verifica os 2, antes de retornar com o resultado.

O que acontece se as senhas forem iguais e/ou a senha antiga estiver errada? Será que tem que colocar os casos de exceção? Só pensei nisso agora. Talvez tivesse que mudar no login caso a senha e/ou cpf estivessem errados.

**Comment by ghost** [comment]
Beleza, ja corrigi isso. Quanto a parte das senhas não serem iguais ou a senha antiga estar errada. teriamos que fazer um diagrama alternativo?

**Comment by marielen** [comment]
Não sei se seria possível colocar no mesmo diagrama. Vou mandar um email pros stakeholders.

**Comment by ghost** [comment]
Subi uma nova versão, se puderem dar uma olhada. Lembrando que seta preenchida é síncrona.

**Comment by marielen** [comment]
Login
- Eu acho que é desnecessário as mensagens 1 e 2, pois acredito que o diagrama de sequencia do login, parte do princípio que o usuário já esteja na tela de login.
- No "3: preencher_login()", teria que ter como argumento cpf e senha, ficando assim "3: login(cpf, senha)"

Alteração de senha
- O mesmo para as mensagens 1 e 2 e para o argumento da mensagem 3.

**Comment by ghost** [comment]
Então, pensei no site ter uma pagina inicial. Que n é necessariamente a tela de login, como a prioridade são as ocorrências a pagina principal ser algo relativo a ela. Dai teria um botão pra ir para pagina de login.

**Comment by marielen** [comment]
Na verdade, não vai ter uma tela de login, pois os funcionários de segurança entram numa página diferente.

Exemplo: Para cadastrar uma ocorrência os usuários irão acessar a página sos.ufrj.br, já os funcionários de segurança irão acessar sos.ufrj.br/admin, assim como está no video.

**Comment by ghost** [comment]
Acabei de subir uma versão, colocando os argumentos cpf e senhas. Mas ainda deixei as mensagens inicias, pq n sei como será a pagina inicial do site.

**Comment by marielen** [comment]
Caso vc suba alguma nova versão lembra de colocar # e o número da issue.

Exemplo: git commit -m "#15 exemplo"

**Comment by ghost** [comment]
Ah sim, eu esqueço desse #11 . Beleza então vou retirar do login, mas a alteração de senha deve permanece, né? porque o funcionário de segurança deve estar na pagina principal dele para poder solicitar a alteração.
