### ISSUE TITLE
Codificar Diagrama de Classes

### ISSUE THREAD

**Issue by marielen** [ESEGroup/Venezuela#9]

**Comment by rdalbuquerque** [comment]
o que seria esse issue??

**Comment by marielen** [comment]
Escrever em python as classes, os métodos e os atributos.

**Comment by rdalbuquerque** [comment]
Isso é p 1a release?

Em 11 de nov de 2016 6:49 PM, "Marielen Ferreira" notifications@github.com
escreveu:

**Comment by marielen** [comment]
Para mim. Pois precisamos disso para fazer o UC01-Cadastro de ocorrências
